url: 'https://sfi0zy.github.io'

host: 0.0.0.0

title: Ivan Bogachev
email: sfi0zy@gmail.com
description: >
    Personal website. I post ideas for front-end developers, CSS, SVG and WebGL animations,
    information about my music, printed books, photography, articles and other projects.

categories: [
    'codepen',
    'dev',
    'publications',
    'other'
]

permalink: /:categories/:title

tags: [
    'html', 'svg', 'css', 'javascript',
    'canvas', 'webgl',
    'animation',
    'math',
    'linux',
    'codepen', 'github', 'habrahabr',
    'publications', 'books',
    'photography', 'psychology', 'music',
    'podcast',
    'other',
]

tags_dir: 'tag'

paginate: 10
paginate_path: '/page:num/'

markdown: kramdown
kramdown:
    syntax_highlighter: rouge

defaults:
    -
        scope:
            path: 'tag'
        values:
            sitemap: false

svg:
    optimize: true

plugins: [
    'jekyll-paginate',
    'jekyll-sitemap',
    'jekyll-inline-svg'
]

exclude:
    - Gemfile
    - Gemfile.lock
    - Makefile
    - packaje-lock.json
    - package.json

